2sum:
	ghc -O3 2SUM.hs

3sum:
	ghc -O3 3SUM.hs

ps:
	ghc -O3 PS.hs

ms:
	ghc -O3 MS.hs

inv:
	ghc -O3 INV.hs

med:
	ghc -O3 MED.hs

clean:
	rm *.hi *.o res

time-2sum:
	time ./2SUM ../data/embiggened

